Repository uswds/uswds-site, pull requests merged in 2020-03, with the labels that each got.

#867 USWDS-Site: Disable forceMediaMerge in CSSO.
  config/gulp/sass.js
Labels: needs: confirmation, needs: feedback, needs: review, needs: testing

#898 Create About “about-test-2”
  pages/about/about-test-2.md
Labels: netlify-cms/pending_publish

#904 Update and improve the local linking instructions
  README.md
Labels: improves: correctness, improves: documentation
