Repository uswds/uswds-site, pull requests merged in 2020-04, with the labels that each got.

#906 Update site name and description
  _config.yml
Labels: improves: documentation, improves: outreach, improves: usability, topic: documentation

#890 USWDS-3350: Update guidance date inputs
  _components/form-controls/05-date-input.md
  package-lock.json
  package.json
Labels: affects: inputs, changes: guidance, changes: interaction, changes: markup

#910 Upgrade axe-core to 3.5+
  _includes/banner.html
  _layouts/landing.html
  package-lock.json
  package.json
  pages/home.md
Labels: improves: accessibility, topic: accessibility, topic: testing

#915 Add slim and no-icon alerts
  _includes/code/components/alerts.html
  package-lock.json
  package.json
Labels: improves: correctness, improves: documentation

#922 Fix output of utility title bars
  _components/utilities/border.md
  _components/utilities/color.md
  _components/utilities/display.md
  _components/utilities/flex.md
  _components/utilities/font-size-and-family.md
  _components/utilities/height-and-width.md
  _components/utilities/list-reset.md
  _components/utilities/margin-and-padding.md
  _components/utilities/paragraph-styles.md
  _components/utilities/shadow.md
  _components/utilities/text-styles.md
  _includes/utilities/utility-title-bar.html
  package-lock.json
  package.json
Labels: improves: correctness, improves: documentation, type: bug
