Repository uswds/uswds-site, pull requests merged in 2020-10, with the labels that each got.

#1073 Update dependencies and DAP subagency
  .nvmrc
  package-lock.json
  package.json
Labels: GSA web mod

#1068 USWDS - Footer: Remove duplicate section.
  _includes/footer.html
  css/_uswds-theme-custom-styles.scss
Labels: affects: footer, improves: correctness

#1064 USWDS - Build : Uninstall node-sass and remove rebuild task from CI.
  .circleci/config.yml
  package.json
Labels: changes: dependencies, topic: dependencies

#1075 Update version of node LTS.
  .nvmrc
Labels: changes: dependencies
