Repository uswds/uswds-site, pull requests merged in 2020-05, with the labels that each got.

#889 [USWDS Site] - Add vision & mission statement.
  pages/about/overview.md
Labels: improves: documentation, topic: documentation

#907 USWDS-Site: Add Twitter link to footer.
  _includes/footer.html
  img/home/icon-twitter.svg
Labels: improves: outreach, topic: outreach

#908 Integrate history content on about landing page
  _data/nav.yml
  pages/about/history.md
  pages/about/overview.md
Labels: improves: documentation, improves: outreach, topic: documentation

#932 USWDS Site: Update labels for consistency.
  _data/nav.yml
  pages/about/overview.md
  pages/about/product-values.html
  pages/about/research.md
  pages/whats-new/overview.md
  pages/whats-new/product-roadmap.md
  pages/whats-new/releases.md
  pages/whats-new/updates.md
Labels: improves: correctness, topic: documentation

#913 Add card component documentation
  _components/card.md
  _data/nav.yml
  _data/variables.yml
  _includes/code/components/card.html
  css/settings/_uswds-theme-components.scss
  package-lock.json
  pages/ui-components/overview.md
Labels: affects: card

#952 USWDS-Site-951 - About: Add missing sidenav on blog posts.
  _posts/2017-03-01-post-1-0-research-strategy-workshop.md
  _posts/2017-03-21-nasa-journey-with-us-web-design-standards.md
  _posts/2017-03-21-update-design-assets.md
  _posts/2017-03-27-u-s-web-design-standards-exposure-analytics.md
  _posts/2017-03-31-u-s-customs-and-border-patrol-case-study.md
  _posts/2017-04-26-fractal-federalist.md
  _posts/2017-06-06-usda-case-study.md
  _posts/2017-06-19-usajobs-case-study.md
  _posts/2017-07-10-vets-case-study.md
  _posts/2017-07-24-code-gov-case-study.md
  _posts/2017-07-25-oes-case-study.md
  _posts/2017-08-14-fec-case-study.md
  _posts/2017-11-08-USAGov-case-study.md
  _posts/2017-12-20-2017-where-weve-been-where-were-going.md
  _posts/2018-01-17-changing-our-name.md
  _posts/2018-02-20-wordpress-theme-benjamin.md
  _posts/2018-02-22-nsf-seed-fund.md
  _posts/2018-03-22-dds-case-study.md
  _posts/2019-04-08-introducing-uswds-2-0.md
Labels: affects: sidenav

#938 USWDS-site data-visualizations: 10x adding guidance and resources for accessible data visualizations
  _components/data-visualizations.md
  _data/nav.yml
  css/_uswds-theme-custom-styles.scss
Labels: affects: data visualization, improves: accessibility, improves: usability, size: days, topic: data visualization
