Repository uswds/uswds-site, pull requests merged in 2024-04, with the labels that each got.

#2636 USWDS-Site: Fix snyk errors
  .snyk
Labels: Added during Sprint

#2576 USWDS-Site: Add February 2024 monthly call
  _data/changelogs/about-monthly-calls.yml
  _data/monthly-calls.yml
  pages/about/monthly-calls.md
Labels: Affects: Content

#2493 USWDS-Site - Display/:Fixes the typo for .z-100
  _utilities/display.md
  pages/design-tokens/z-index.md
Labels: Is: Typo, Affects: Guidance
