Repository uswds/uswds-site, pull requests merged in 2024-10, with the labels that each got.

#2776 Form component: Updated Disabled States guidance
  _data/changelogs/component-form.yml
  _includes/forms-guidance.html
Labels: Affects: Accessibility 🟡, Affects: Content, Affects: Guidance, Affects: Usability

#2812 USWDS-Site: Documentation updates for 3.9.0
  _config.yml
  _data/accessibility-tests/footer.yml
  _data/changelogs/component-alert.yml
  _data/changelogs/component-button.yml
  _data/changelogs/component-card.yml
  _data/changelogs/component-character-count.yml
  _data/changelogs/component-combo-box.yml
  _data/changelogs/component-date-picker.yml
  _data/changelogs/component-date-range-picker.yml
  _data/changelogs/component-footer-accessibility.yml
  _data/changelogs/component-footer.yml
  _data/changelogs/component-header.yml
  _data/changelogs/component-identifier.yml
  _data/changelogs/component-memorable-date.yml
  _data/changelogs/component-pagination.yml
  _data/changelogs/component-site-alert.yml
  _data/changelogs/docs-settings.yml
  _data/changelogs/template-create-account.yml
  _data/settings/utilities.yml
  package-lock.json
  package.json
Labels: Added during Sprint

#2848 USWDS-Site - Bug: Update chat.18f.gov links to go to 18f.gov/chat
  pages/about/community.md
Labels: Type: Bug, Affects: Content

#2744 Update Complex Form: Progress Easily with Disabled States guidance
  _data/changelogs/pattern-complex-form-establish-trust.yml
  _data/changelogs/pattern-complex-form-keep-a-record.yml
  _data/changelogs/pattern-complex-form-progress-easily.yml
  pages/patterns/complex-form/establish-trust.md
  pages/patterns/complex-form/progress-easily.md
Labels: Affects: Content, Affects: Usability

#2873 Add August MC video to Monthly Calls page
  _data/changelogs/about-monthly-calls.yml
  _data/monthly-calls.yml
Labels: Affects: Content
